### ISSUE TITLE
Uncaught exception 'TransmissionRPCException' with message 'Invalid username/password

### ISSUE THREAD

**Issue by Nurza** [brycied00d/PHP-Transmission-Class#22]
Hello, i wanted to use your class, but i can't connect to my transmission server.

Here is the tests.php : 

```
#!/usr/bin/php
<?php

require_once( dirname( __FILE__ ) . '/class/TransmissionRPC.class.php' );

$test_torrent = "http://releases.ubuntu.com/trusty/ubuntu-14.04-desktop-amd64.iso.torrent";

$rpc = new TransmissionRPC();
$rpc->username = 'admin';
$rpc->password = 'lala';
$rpc->debug = true;

try
{
  $result = $rpc->add( $test_torrent, '/tmp' );
  $id = $result->arguments->torrent_added->id;
  print "ADD TORRENT TEST... [{$result->result}] (id=$id)\n";

  sleep( 2 );

  $result = $rpc->set( $id, array('uploadLimit' => 10) );
  print "SET TORRENT INFO TEST... [{$result->result}]\n";

  sleep( 2 );

  $rpc->return_as_array = true;
  $result = $rpc->get( $id, array( 'uploadLimit' ) );
  print "GET TORRENT INFO AS ARRAY TEST... [{$result['result']}]\n";
  $rpc->return_as_array = false;

  sleep( 2 );

  $result = $rpc->get( $id, array( 'uploadLimit' ) );
  print "GET TORRENT INFO AS OBJECT TEST... [{$result->result}]\n";
  
  sleep( 2 );
  
  $result2 = $result->arguments->torrents[0]->uploadLimit == 10 ? 'success' : 'failed';
  print "VERIFY TORRENT INFO SET/GET... [{$result2}] (".$result->arguments->torrents[0]->uploadLimit.")\n";

  $result = $rpc->stop( $id );
  print "STOP TORRENT TEST... [{$result->result}]\n";
  sleep( 2 );

  $result = $rpc->verify( $id );
  print "VERIFY TORRENT TEST... [{$result->result}]\n";

  sleep( 10 );

  $result = $rpc->start( $id );
  print "START TORRENT TEST... [{$result->result}]\n";

  sleep( 2 );

  $result = $rpc->reannounce( $id );
  print "REANNOUNCE TORRENT TEST... [{$result->result}]\n";

  sleep( 2 );

  $result = $rpc->move( $id, '/tmp/torrent-test', true );
  print "MOVE TORRENT TEST... [{$result->result}]\n";

  sleep( 2 );

  $result = $rpc->remove( $id, false );
  print "REMOVE TORRENT TEST... [{$result->result}]\n";
  
} catch (Exception $e) {
  die('[ERROR] ' . $e->getMessage() . PHP_EOL);
}

?>
```

And the transmission config file:
```
{
    "alt-speed-down": 50, 
    "alt-speed-enabled": false, 
    "alt-speed-time-begin": 540, 
    "alt-speed-time-day": 127, 
    "alt-speed-time-enabled": false, 
    "alt-speed-time-end": 1020, 
    "alt-speed-up": 50, 
    "bind-address-ipv4": "0.0.0.0", 
    "bind-address-ipv6": "::", 
    "blocklist-enabled": false, 
    "blocklist-url": "http://www.example.com/blocklist", 
    "cache-size-mb": 4, 
    "dht-enabled": true, 
    "download-dir": "/var/lib/transmission-daemon/downloads", 
    "download-limit": 100, 
    "download-limit-enabled": 0, 
    "download-queue-enabled": true, 
    "download-queue-size": 5, 
    "encryption": 1, 
    "idle-seeding-limit": 30, 
    "idle-seeding-limit-enabled": false, 
    "incomplete-dir": "/home/debian-transmission/Downloads", 
    "incomplete-dir-enabled": false, 
    "lpd-enabled": false, 
    "max-peers-global": 200, 
    "message-level": 2, 
    "peer-congestion-algorithm": "", 
    "peer-id-ttl-hours": 6, 
    "peer-limit-global": 200, 
    "peer-limit-per-torrent": 50, 
    "peer-port": 51413, 
    "peer-port-random-high": 65535, 
    "peer-port-random-low": 49152, 
    "peer-port-random-on-start": false, 
    "peer-socket-tos": "default", 
    "pex-enabled": true, 
    "port-forwarding-enabled": false, 
    "preallocation": 1, 
    "prefetch-enabled": 1, 
    "queue-stalled-enabled": true, 
    "queue-stalled-minutes": 30, 
    "ratio-limit": 2, 
    "ratio-limit-enabled": false, 
    "rename-partial-files": true, 
    "rpc-authentication-required": true, 
    "rpc-bind-address": "0.0.0.0", 
    "rpc-enabled": true, 
    "rpc-password": "{d1f76d377b9b3ef4f83504e30cc45deb5cf6ee14ruaQpIDy", 
    "rpc-port": 9091, 
    "rpc-url": "/transmission/", 
    "rpc-username": "admin", 
    "rpc-whitelist": "127.0.0.1", 
    "rpc-whitelist-enabled": false, 
    "scrape-paused-torrents-enabled": true, 
    "script-torrent-done-enabled": false, 
    "script-torrent-done-filename": "", 
    "seed-queue-enabled": false, 
    "seed-queue-size": 10, 
    "speed-limit-down": 100, 
    "speed-limit-down-enabled": false, 
    "speed-limit-up": 100, 
    "speed-limit-up-enabled": false, 
    "start-added-torrents": true, 
    "trash-original-torrent-files": false, 
    "umask": 18, 
    "upload-limit": 100, 
    "upload-limit-enabled": 0, 
    "upload-slots-per-torrent": 14, 
    "utp-enabled": true
}
```

I have tested in chromium browser, the login and the password work, but when i go to the tests.php page, apache write this to the error.log :

```
[Thu Jul 31 20:50:33.896834 2014] [:error] [pid 25464] [client 93.13.102.4:33051] PHP Fatal error:  Uncaught exception 'TransmissionRPCException' with message 'Invalid username/password.' in /var/www/html/trans/PHP-Transmission-Class/class/TransmissionRPC.class.php:557\nStack trace:\n#0 /var/www/html/trans/PHP-Transmission-Class/class/TransmissionRPC.class.php(471): TransmissionRPC->GetSessionID()\n#1 /var/www/html/trans/PHP-Transmission-Class/class/TransmissionRPC.class.php(337): TransmissionRPC->request('session-get', Array)\n#2 /var/www/html/trans/PHP-Transmission-Class/class/TransmissionRPC.class.php(599): TransmissionRPC->sget()\n#3 /var/www/html/trans/PHP-Transmission-Class/tests.php(8): TransmissionRPC->__construct()\n#4 {main}\n  thrown in /var/www/html/trans/PHP-Transmission-Class/class/TransmissionRPC.class.php on line 557
```

Thank you.

**Comment by gbejic** [comment]
This didn't work for me either 
{code}
$rpc = new TransmissionRPC();
$rpc->username = 'admin';
$rpc->password = 'lala';
$rpc->debug = true;
{code}

but if i call 
{code}
$rpc = new TransmissionRPC($url, $user, $pass);
{code}
works like a charm. 
Thank you for your Transmission class
